# Generated by Django 5.0 on 2023-12-05 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_municipality_fk', to='settings.municipality'),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_province_fk', to='settings.province'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='client_user_logged_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contracts.client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract',
            field=models.ForeignKey(help_text='Contrato primario', on_delete=django.db.models.deletion.RESTRICT, related_name='contract_contract_fk', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_user_manager_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_receiving',
            field=models.ForeignKey(help_text='Usuario que registro el servicio', on_delete=django.db.models.deletion.RESTRICT, related_name='contract_user_receiving_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contracts.client'),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='settings.servicetype'),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_service_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contract_status_contract_fk', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contract_status_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offer_client_fk', to='contracts.client'),
        ),
        migrations.AddField(
            model_name='offer',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offer_contract_fk', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offer_service_fk', to='settings.servicetype'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='work_order_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='user_client_receiving',
            field=models.ForeignKey(help_text='Especialista comercial que entrega', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offer_user_client_receiving_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='user_receiving',
            field=models.ForeignKey(help_text='Especialista comercial que recibe', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offer_user_receiving_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerstatus',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offer_status_contract_fk', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='offerstatus',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offer_status_contract_fk', to='contracts.offer'),
        ),
        migrations.AddField(
            model_name='offerstatus',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offer_status_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_contract_fk', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_client_fk', to='contracts.client'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_approved',
            field=models.ForeignKey(help_text='Usuario que registro el servicio', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_user_approved_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_assigned',
            field=models.ForeignKey(help_text='Usuario que registro el servicio', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_user_aproved_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_request_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user_receiving',
            field=models.ForeignKey(help_text='Usuario que registro el servicio', on_delete=django.db.models.deletion.RESTRICT, related_name='service_user_receiving_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contracts.servicerequest'),
        ),
    ]
