# Generated by Django 5.0 on 2023-12-06 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
        ('settings', '0003_alter_servicetype_name_ministery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ministry',
            field=models.ForeignKey(help_text='Organismo al que pertenece la empresa', on_delete=django.db.models.deletion.RESTRICT, to='settings.ministry'),
        ),
    ]
