# Generated by Django 5.0 on 2023-12-05 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groupuser',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='groupuser',
            name='user_at',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GroupUser_user_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='groupuser',
            table='tb_group_users',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Group_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_groups',
            },
        ),
        migrations.AddField(
            model_name='groupuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GroupUser_group_fk', to='settings.group'),
        ),
    ]
