# Generated by Django 5.0 on 2023-12-06 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_customuser_groupuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acronym', models.CharField(help_text='Siglas o acronico del organismo', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Ministry_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_ministeries',
            },
        ),
    ]
